---
apiVersion: v1
kind: Service
metadata:
  name: historical-lb
  labels:
    app: historical
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    name: http-exporter
  selector:
    app: historical
