---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coordinator
spec:
  template:
    spec:
      containers:
      - name: service
        ports:
        - name: overlord
          containerPort: 8090
