---
apiVersion: v1
kind: ConfigMap
metadata:
  name: middlemanager
data:
  supervise.conf: |
    :verify bin/verify-java

    middleManager bin/run-druid middleManager conf/mounted/service

  runtime.properties: |
    druid.service=druid/middleManager
    druid.plaintextPort=8091

    # Number of tasks per middleManager
    druid.worker.capacity=4

    # Task launch parameters
    druid.indexer.runner.javaOpts=-server -Xms1g -Xmx1g -XX:MaxDirectMemorySize=1g -Duser.timezone=UTC -Dfile.encoding=UTF-8 -XX:+ExitOnOutOfMemoryError -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
    druid.indexer.task.baseTaskDir=/var/druid/task

    # HTTP server threads
    druid.server.http.numThreads=60

    # Processing threads and buffers on Peons
    druid.indexer.fork.property.druid.processing.numMergeBuffers=2
    druid.indexer.fork.property.druid.processing.buffer.sizeBytes=100000000
    druid.indexer.fork.property.druid.processing.numThreads=1

    # Hadoop indexing
    druid.indexer.task.hadoopWorkingPath=/var/druid/hadoop-tmp

  jvm.config: |
    -server
    -Xms128m
    -Xmx128m
    -XX:+ExitOnOutOfMemoryError
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -Djava.io.tmpdir=var/tmp
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager

  main.config: |
    org.apache.druid.cli.Main server middleManager

---
apiVersion: v1
kind: Service
metadata:
  name: middlemanager
  labels:
    app: middlemanager
spec:
  ports:
  - port: 8091
    name: middlemanager
  selector:
    app: middlemanager
---
apiVersion: v1
kind: Service
metadata:
  name: middlemanager-headless
  labels:
    app: middlemanager
spec:
  clusterIP: None
  ports:
  - port: 8091
    name: middlemanager
  selector:
    app: middlemanager
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: middlemanager
spec:
  selector:
    matchLabels:
      app: middlemanager
  serviceName: middlemanager-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: middlemanager
    spec:
      containers:
      - name: coordinator
        imagePullPolicy: Never
        image: dmarkwat.io/apache/druid
        resources:
          requests:
            memory: 4G
            cpu: 2000m
        args:
        - -c
        - /druid/conf/mounted/service/middleManager/supervise.conf
        - --stdout
        ports:
        - name: middlemanager
          containerPort: 8091
        volumeMounts:
        - name: common
          mountPath: /druid/conf/mounted/service/_common
        - name: service
          mountPath: /druid/conf/mounted/service/middleManager
        - name: druiddata
          mountPath: /var/druid
      volumes:
      - name: common
        configMap:
          name: common
      - name: service
        configMap:
          name: middlemanager
      - name: druiddata
        persistentVolumeClaim:
          claimName: shared
  # volumeClaimTemplates:
  # - metadata:
  #     name: druiddata
  #   spec:
  #     accessModes: ["ReadWriteMany"]
  #     volumeName: shared
  #     resources:
  #       requests:
  #         storage: 1Gi
