resources:
  - ../../bases/common
  - volumes.yml
  configMapGenerator:
  - name: common
    behavior: merge
    files:
    - common.runtime.properties
    - log4j2.xml
patchesStrategicMerge:
- | -
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: druid
    annotations:
      iam.gke.io/gcp-service-account=druid@myproject.iam.gserviceaccount.com
