apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: regional-standard
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared
spec:
  storageClassName: regional-standard
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Ti
