---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: middlemanager
spec:
  template:
    spec:
      containers:
      - name: service
        resources:
          requests:
            memory: 8G
            cpu: 4000m
  volumeClaimTemplates:
  - metadata:
      name: druiddata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
