namespace: druid
resources:
- namespace.yml
- zookeeper
- postgres
- common
- coordinator-overlord
- historical
- middlemanager
- broker
- router
patches:
- target:
    kind: StatefulSet
    labelSelector: app notin (zk,postgresql)
  path: image_policy.yml
- target:
    kind: StatefulSet
    labelSelector: app notin (zk,postgresql)
  path: pod_sec.yml
- target:
    kind: StatefulSet
    labelSelector: app notin (zk,postgresql)
  path: shared_volume.yml
- target:
    kind: StatefulSet
    labelSelector: app notin (zk,postgresql)
  path: common_config.yml
- target:
    kind: StatefulSet
    labelSelector: app notin (zk,postgresql)
  path: exporter.yml
images:
- name: apache/druid
  newTag: 0.19.0
- name: wikimedia/druid_exporter
  # update these with whatever was published to the docker repo
  newDigest: sha256:change-me
  newName: change-me
