---
apiVersion: v1
kind: ConfigMap
metadata:
  name: historical
data:
  supervise.conf: |
    :verify bin/verify-java

    historical bin/run-druid historical conf/mounted/service

  runtime.properties: |
    druid.service=druid/historical
    druid.plaintextPort=8083

    # HTTP server threads
    druid.server.http.numThreads=12

    # Processing threads and buffers
    druid.processing.buffer.sizeBytes=200000000
    druid.processing.numMergeBuffers=2
    druid.processing.numThreads=2
    druid.processing.tmpDir=/var/druid/processing

    # Segment storage
    druid.segmentCache.locations=[{"path":"/var/druid/segment-cache","maxSize":300000000000}]
    druid.server.maxSize=300000000000

    # Query cache
    druid.historical.cache.useCache=true
    druid.historical.cache.populateCache=true
    druid.cache.type=caffeine
    druid.cache.sizeInBytes=10000000

  jvm.config: |
    -server
    -XX:+UnlockExperimentalVMOptions
    -XX:MaxRAMPercentage=0.5
    -XX:MaxDirectMemorySize=1280m
    -XX:+ExitOnOutOfMemoryError
    -XX:+UseG1GC
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -Djava.io.tmpdir=var/tmp
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager

  main.config: |
    org.apache.druid.cli.Main server historical

---
apiVersion: v1
kind: Service
metadata:
  name: historical
  labels:
    app: historical
spec:
  ports:
  - port: 8083
    name: historical
  selector:
    app: historical
---
apiVersion: v1
kind: Service
metadata:
  name: historical-headless
  labels:
    app: historical
spec:
  clusterIP: None
  ports:
  - port: 8083
    name: historical
  selector:
    app: historical
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: historical
spec:
  selector:
    matchLabels:
      app: historical
  serviceName: historical-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: historical
    spec:
      containers:
      - name: coordinator
        imagePullPolicy: Never
        image: dmarkwat.io/apache/druid
        resources:
          requests:
            memory: 2G
            cpu: 750m
        args:
        - -c
        - /druid/conf/mounted/service/historical/supervise.conf
        - --stdout
        ports:
        - name: historical
          containerPort: 8083
        volumeMounts:
        - name: common
          mountPath: /druid/conf/mounted/service/_common
        - name: service
          mountPath: /druid/conf/mounted/service/historical
        - name: druiddata
          mountPath: /var/druid
      volumes:
      - name: common
        configMap:
          name: common
      - name: service
        configMap:
          name: historical
      - name: druiddata
        persistentVolumeClaim:
          claimName: shared
  # volumeClaimTemplates:
  # - metadata:
  #     name: druiddata
  #   spec:
  #     accessModes: ["ReadWriteMany"]
  #     volumeName: shared
  #     resources:
  #       requests:
  #         storage: 1Gi
