resources:
- ../../bases/coordinator-overlord
- service.yml
patchesStrategicMerge:
- patch.yml
configMapGenerator:
- name: coordinator
  behavior: merge
  files:
  - jvm.config
  - runtime.properties
