---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/druid/shared001/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: shared
