---
apiVersion: v1
kind: Service
metadata:
  name: router-lb
  labels:
    app: router
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    name: router
  selector:
    app: router
