---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
spec:
  template:
    spec:
      containers:
      - name: kubernetes-zookeeper
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
