---
apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    app: router
spec:
  ports:
  - port: 8888
    name: router
  selector:
    app: router
---
apiVersion: v1
kind: Service
metadata:
  name: router-headless
  labels:
    app: router
spec:
  clusterIP: None
  ports:
  - port: 8888
    name: router
  selector:
    app: router
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: router
spec:
  selector:
    matchLabels:
      app: router
  serviceName: router-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: service
        image: apache/druid
        resources:
          requests:
            memory: 256M
            cpu: 750m
        args:
        - router
        ports:
        - name: router
          containerPort: 8888
        volumeMounts:
        - name: service
          mountPath: /druid/conf/mounted/service/router
      volumes:
      - name: service
        configMap:
          name: router
