apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: druid
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: postgresql
    version: 8.4.0
  values:
    postgresqlUsername: postgres
    postgresqlPassword: postgres
    postgresqlDatabase: druid
    serviceAccount:
      enabled: true
